import Projects from 'components/project/Projects';
import Head from 'next/head';

export default function Home() {

	return (
		<div className='container has-top-margin'>
			<Head>
				<title>Frank Alvarez</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className='iam'>
				<h1>Frank Alvarez</h1>
				<div className='iam-description'>
					Desarrollador frontend
				</div>
			</div>
			<div className='section' id='proyectos'>
				<h2>
					Proyectos
				</h2>
				<Projects />
			</div>
			<div className='section' id='sobremi'>
				<h2>
					Sobre mi
				</h2>
				<p className='opacity:1'>
					Soy un desarrollador frontend junior, conozco tecnologías como reactjs y vuejs.
				</p>
			</div>
		</div>
	)
}
