import Projects from 'components/project/projects';
import Head from 'next/head';

export default function Home() {

	return (
		<div className='container has-top-margin'>
			<Head>
				<title>Frank Alvarez</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className='text-align:center'>
				<h1>Frank Alvarez</h1>
				<p>
					Developer
				</p>
			</div>
			<div>
				<h2>
					Portafolio
				</h2>
				<Projects/>
			</div>
		</div>
	)
}
