import Projects from 'components/project/Projects';
import Head from 'next/head';

export default function Home() {

	return (
		<div className='container has-top-margin'>
			<Head>
				<title>Frank Alvarez</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className='iam'>
				<h1>Frank Alvarez</h1>
				<div className='iam-description'>
					Desarrollador frontend
				</div>
			</div>
			<div className='section' id='proyectos'>
				<h2 className='mg-bottom:lg'>
					Proyectos
				</h2>
				<Projects />
			</div>
			<div className='section' id='sobremi'>
				<h2>
					Sobre mi
				</h2>
				<p className='opacity:1'>
					Programador frontend, con un año de experiencia usando Vanilla JavaScript y tecnologías como Vue JS y React JS.
					Soy empático con los demás, también me gusta aprender y probar nuevas tecnologías.
				</p>
			</div>
		</div>
	)
}
